### PR TITLE
ElGamal normal

### PR DESCRIPTION
**Pull request by mikecmtong**
Implements ((kind of jankily but it's ok)) the ElGamal asymmetric encryption/decryption scheme. Works like this:

TERMINAL 1:
[C program: Reads from stdin and prints int values associated to the chars of the string to stdout] 
Connected to...

TERMINAL 2 (Bob):
[C% program: Takes these char values and prints the encrypted value]
Connected to...

TERMINAL 3 (Alice):
[C% program: Takes these encrypted char values and prints the decrypted value]
Connected to...

TERMINAL 4:
[C program: Reads from stdin and prints the chars associated to these values]

The branch was called "EC" because I was originally planning on doing it with ECC, but forgot that we would need to encode the messages on an Elliptic Curve using the Koblitz method, which I didn't feel like doing. shrug

### CODE REVIEW

**Comment by joshuazweig** [comment]
Super cool, awesome stuff @mikecmtong 

Can we change the C% programs to the .cm extension? Also let's make sure to add atoi to the LRM/final report

**Comment by joshuazweig** [comment]
Is there a particular reason for having the bob-bob and alice-alice nc sessions? Is it for effect?
If not, can you just use a piping scheme?

**Comment by mikecmtong** [comment]
Yeah I can change the file names.

Are you referring to the terminal 2 and terminal 4? The idea is that you can see the stream of chars they receive in terms of their numeric values, since they are more closely related to the stream of encrypted chars that they pass between them (we can't just print the encrypted chars since 1) many of them would be unprintable chars and 2) many of them have values larger than 256).

**Comment by joshuazweig** [comment]
Understood. I do think it might look cool for the demo though if we just print a bunch of unprintable chars to the screen and tee them straight into our program. 
Let's merge for now and we can discuss tomorrow.

**Comment by mikecmtong** [comment]
Yeah I was thinking about that but a lot of the chars are not within char range so doesn't work

**Comment by joshuazweig** [comment]
Just did a test and you can def print unprintable chars ( I think it just
does it mod 256 ). See below

[joshua ?] $ cat x.c

#include<stdio.h>

int main()

{

char c = 300;

printf("%c\n\n", c);

}

joshuazweig@dyn-160-39-141-238:~

[joshua ?] $ gcc x.c

x.c:4:11: warning: implicit conversion from 'int' to 'char' changes value
from

      300 to 44 [-Wconstant-conversion]

        char c = 300;

             ~   ^~~

1 warning generated.

joshuazweig@dyn-160-39-141-238:~

[joshua ?] $ ./a.out

,

**Pull request merged**
