### PR TITLE
Python preprocessor working.

### PR DESCRIPTION
**Pull request by mikecmtong**
Use # followed by...

include "filename": runs the preprocessor on the file specified by
filename, replacing #include statement with the result

define SYMBOL: adds SYMBOL to preprocessor's table (cf. ifdef, ifndef).
Note: not useful for textual substitutions (e.g. #ifdef CONSTANT 42)

ifdef SYMBOL: if SYMBOL is in preprocessor's table, continue. else, skip
lines until #endif is found

ifndef SYMBOL: opposite of ifdef

endif: only relevant in the ifdef/ifndef cases above

### CODE REVIEW

**Comment by mlm2299** [comment]
is there a reason you changed the llvm version?

**Comment by joshuazweig** [comment]
Getting an error when I try to test. 
Is the correct workflow
1. Run the python script on the .cm file
2. run cmod.sh on the file it outputs

**Comment by zsilber** [comment]
Workflow seems to be to run
'python preprocessor.py prepro_test.cm'
Which gives prepro_test_preprocess.cm

Is there any way to make the user not have to manually do this? Through the cmod.sh and a library of stuff like myadd? Also kinda weird that the preprocessed version is also in this commit.

Preprocessor definitely works, just weirdly integrated right now.

**Comment by joshuazweig** [comment]
@Zack we can handle it in the shell script that runs the program no
problem. Was going to do it last night but I couldn't get the test to work.
I'm OK merging for now if youre happy with it and I can add that in later.

Do you have any ideas on how we should write tests for this?

**Comment by zack** [comment]
@joshuazweig @zsilber ^^ ;) ;)

**Comment by zsilber** [comment]
Yeah, I'm okay with merging cleaning up some stuff right now, but I'll commit a change soon for this PR.

Testing it is going to depend on how we ultimately run these files. Are we going to start preprocessing everything?

**Comment by joshuazweig** [comment]
Cool lets merge

**Pull request merged**
